# Generated by Django 3.2.9 on 2021-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationApp', '0002_operationtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtransaction',
            name='after',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationtransaction',
            name='before',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operationtransaction',
            name='operation',
            field=models.CharField(choices=[('REVERSE', 'REVERSE'), ('REVERSE WORD', 'REVERSE WORD'), ('FLIP BREAK', 'FLIP BREAK'), ('SORT CHARACTERS', 'SORT CHARACTERS')], max_length=20),
        ),
    ]
